from models.base import Basevn
from libs.workflow import get_workflows

Workflows: Basevn = {
    "name": "Workflow_Workflows",
    "get": get_workflows,
    "transform": lambda rows: rows,
    "schema": [
        {"name": "id", "type": "INTEGER"},
        {"name": "type", "type": "STRING"},
        {"name": "hid", "type": "STRING"},
        {"name": "token", "type": "STRING"},
        {"name": "status", "type": "INTEGER"},
        {"name": "state", "type": "STRING"},
        {"name": "starred", "type": "INTEGER"},
        {"name": "name", "type": "STRING"},
        {"name": "title", "type": "STRING"},
        {"name": "content", "type": "STRING"},
        {"name": "color", "type": "INTEGER"},
        {"name": "followers", "type": "STRING", "mode": "REPEATED"},
        {"name": "since", "type": "TIMESTAMP"},
        {"name": "last_update", "type": "TIMESTAMP"},
        {"name": "finish_at", "type": "TIMESTAMP"},
        {"name": "stage_id", "type": "INTEGER"},
        {
            "name": "stage_export",
            "type": "RECORD",
            "fields": [
                {"name": "id", "type": "INTEGER"},
                {"name": "name", "type": "STRING"},
                {"name": "metatype", "type": "STRING"},
                {"name": "workflow_id", "type": "INTEGER"},
                {"name": "type", "type": "STRING"},
            ],
        },
        {
            "name": "stats",
            "type": "RECORD",
            "fields": [
                {"name": "notes", "type": "INTEGER"},
                {"name": "posts", "type": "INTEGER"},
                {"name": "files", "type": "INTEGER"},
                {"name": "likes", "type": "INTEGER"},
            ],
        },
        {"name": "user_id", "type": "INTEGER"},
        {"name": "username", "type": "STRING"},
        {
            "name": "todos",
            "type": "RECORD",
            "mode": "REPEATED",
            "fields": [
                {"name": "id", "type": "INTEGER"},
                {"name": "name", "type": "STRING"},
                {"name": "status", "type": "INTEGER"},
                {"name": "stage_id", "type": "INTEGER"},
                {"name": "deadline", "type": "TIMESTAMP"},
                {"name": "username", "type": "STRING"},
                {"name": "type", "type": "STRING"},
                {"name": "link", "type": "STRING"},
            ],
        },
        {"name": "creator_id", "type": "INTEGER"},
        {"name": "creator_username", "type": "STRING"},
        {"name": "deadline", "type": "INTEGER"},
        {"name": "stage_deadline", "type": "TIMESTAMP"},
        {"name": "stage_start", "type": "TIMESTAMP"},
        {"name": "workflow_id", "type": "INTEGER"},
        {
            "name": "workflow_export",
            "type": "RECORD",
            "fields": [
                {"name": "id", "type": "INTEGER"},
                {"name": "name", "type": "STRING"},
                {"name": "type", "type": "STRING"},
            ],
        },
        {
            "name": "moves",
            "type": "RECORD",
            "mode": "REPEATED",
            "fields": [
                {"name": "id", "type": "INTEGER"},
                {"name": "user_id", "type": "INTEGER"},
                {"name": "mover_id", "type": "INTEGER"},
                {"name": "job_id", "type": "INTEGER"},
                {"name": "stage_id", "type": "INTEGER"},
                {"name": "stage_start", "type": "TIMESTAMP"},
                {"name": "stage_deadline", "type": "TIMESTAMP"},
                {"name": "from_stage_id", "type": "INTEGER"},
                {"name": "duration", "type": "INTEGER"},
                {"name": "past", "type": "INTEGER"},
                {"name": "stage_end", "type": "TIMESTAMP"},
            ],
        },
        {
            "name": "acl",
            "type": "RECORD",
            "fields": [
                {"name": "view", "type": "INTEGER"},
                {"name": "status", "type": "INTEGER"},
                {"name": "managed", "type": "INTEGER"},
                {"name": "edit", "type": "INTEGER"},
            ],
        },
        {
            "name": "form",
            "type": "RECORD",
            "mode": "REPEATED",
            "fields": [
                {"name": "id", "type": "STRING"},
                {"name": "name", "type": "STRING"},
                {"name": "value", "type": "STRING"},
                {"name": "type", "type": "STRING"},
                {"name": "placeholder", "type": "STRING"},
            ],
        },
        {
            "name": "on_failed",
            "type": "RECORD",
            "fields": [
                {"name": "stage_id", "type": "INTEGER"},
                {"name": "failed_reason_id", "type": "STRING"},
                {"name": "failed_name", "type": "STRING"},
                {"name": "note", "type": "STRING"},
                {"name": "since", "type": "TIMESTAMP"},
            ],
        },
        {
            "name": "data",
            "type": "RECORD",
            "fields": [
                {"name": "deadline_by_timesheet", "type": "INTEGER"},
                {"name": "first_assignee", "type": "INTEGER"},
                {"name": "last_assignee", "type": "INTEGER"},
            ],
        },
        {"name": "keyword", "type": "STRING"},
        {"name": "deadline_by_timesheet", "type": "INTEGER"},
        {"name": "first_assignee", "type": "INTEGER"},
    ],
}
